# Intelligent Employee Policy Assistant – Chunking Analysis

## Problem Statement

A company wants to build an AI-powered Employee Policy Assistant using Retrieval-Augmented Generation (RAG).

The organization maintains multiple policy documents:

- Employee Handbook
- Leave Policy
- Travel Policy
- Work From Home Policy
- Medical Insurance Policy

Before implementing the RAG pipeline, the company wants to evaluate different document chunking strategies and determine the most effective approach for information retrieval.

Your task is to load the policy document, implement multiple chunking techniques, analyze the generated chunks, and identify the most suitable chunking strategy for enterprise RAG systems.

---

## Dataset

Create a PDF document containing the following sections:

### Leave Policy
- Employees receive 12 casual leaves annually.
- Employees receive 15 sick leaves annually.
- Unused casual leaves cannot be carried forward.

### Work From Home Policy
- Employees may work from home twice per week.
- Manager approval is required for additional remote work.

### Travel Policy
- Travel expenses are reimbursed within 30 days.
- Original receipts must be submitted for reimbursement.

### Medical Insurance Policy
- All employees are covered under company medical insurance.
- Dependent coverage is available for spouse and children.

---

## Task 1: PDF Loading

### Objective
Load and extract text from the PDF document.

### Deliverables
Display:
- Original Document
- Total Characters
- Total Words

---

## Task 2: Fixed Size Chunking

### Objective
Implement Fixed Size Chunking.

### Requirements
Create chunks using:
- Chunk Size = 100
- Chunk Size = 200
- Chunk Size = 300

### Deliverables
Display:
- Chunk Number
- Chunk Content
- Chunk Length

### Analysis
Answer:
- Are sentences being split?
- Is context preserved?
- What are the limitations?

---

## Task 3: Recursive Chunking

### Objective
Implement Recursive Character Chunking using LangChain.

### Requirements
Experiment with:
- Chunk Size = 200, Chunk Overlap = 20
- Chunk Size = 200, Chunk Overlap = 50
- Chunk Size = 300, Chunk Overlap = 50

### Deliverables
Display:
- Chunk Number
- Chunk Content

### Analysis
Explain:
- How overlap improves context retention.

---

## Task 4: Sentence-Based Chunking

### Objective
Implement Sentence Chunking.

### Requirements
Split the document into sentences using NLTK or SpaCy.

### Deliverables
Display:
- Sentence Number
- Sentence Content

### Analysis
Answer:
- Does sentence chunking preserve meaning better than fixed-size chunking?

---

## Task 5: Semantic Chunking

### Objective
Group content based on meaning.

### Example Output

#### Chunk 1: Leave Policy Section

#### Chunk 2: Work From Home Policy Section

#### Chunk 3: Travel Policy Section

#### Chunk 4: Medical Insurance Policy Section

### Deliverables
Display:
- Semantic Chunk Number
- Semantic Chunk Content

### Analysis
Explain:
- Why semantic chunking may improve retrieval quality.

---

## Task 6: Chunk Comparison

### Objective
Compare all chunking techniques.

Create a table:

| Chunking Method | Context Preservation | Retrieval Quality | Implementation Complexity |
|----------------|----------------------|------------------|--------------------------|
| Fixed Size | ? | ? | ? |
| Recursive | ? | ? | ? |
| Sentence | ? | ? | ? |
| Semantic | ? | ? | ? |

---

## Task 7: Retrieval Simulation

### Objective
Test retrieval effectiveness.

### Queries
1. How many casual leaves are provided?
2. Can employees work from home?
3. What is the travel reimbursement process?
4. Who is covered under medical insurance?

### Requirements
For each chunking strategy:
- Retrieve the most relevant chunk.

### Deliverables
Display:
- Query
- Retrieved Chunk
- Chunking Method

---

## Task 8: Recommendation Report

### Objective
Act as an AI Engineer.

Prepare a report answering:

### Which chunking strategy would you use for:
- HR Policy Assistant
- Legal Document Assistant
- Medical Document Assistant
- Research Paper Assistant

### Justify your answers.

In [2]:
from reportlab.pdfgen import canvas

pdf_file = "employee_policy.pdf"

c = canvas.Canvas(pdf_file)

content = """
Leave Policy

Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.

Work From Home Policy

Employees may work from home twice per week.
Manager approval is required for additional remote work.

Travel Policy

Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.

Medical Insurance Policy

All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.
"""

y = 800

for line in content.split("\n"):
    c.drawString(50, y, line)
    y -= 20

c.save()

print("PDF Created Successfully")

PDF Created Successfully

In [3]:
from PyPDF2 import PdfReader

reader = PdfReader("employee_policy.pdf")

text = ""

for page in reader.pages:
    text += page.extract_text()

print(text)

Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

In [4]:
print("Original Document:\n")
print(text)

print("\nTotal Characters:", len(text))
print("Total Words:", len(text.split()))

Original Document:

Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.


Total Characters: 530
Total Words: 76

# *Task 2: Fixed Size Chunking*

In [5]:
def fixed_chunk(text, chunk_size):
    chunks = []

    for i in range(0, len(text), chunk_size):
        chunks.append(text[i:i+chunk_size])

    return chunks

In [6]:
for size in [100,200,300]:

    print(f"\n\nChunk Size = {size}")

    chunks = fixed_chunk(text,size)

    for i,chunk in enumerate(chunks):

        print("\nChunk Number:",i+1)
        print(chunk)
        print("Chunk Length:",len(chunk))

Chunk Size = 100

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Chunk Length: 100

Chunk Number: 2

Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home
Chunk Length: 100

Chunk Number: 3
twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expens
Chunk Length: 100

Chunk Number: 4
es are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Ins
Chunk Length: 100

Chunk Number: 5
urance Policy
All employees are covered under company medical insurance.
Dependent coverage is avail
Chunk Length: 100

Chunk Number: 6
able for spouse and children.

Chunk Length: 30


Chunk Size = 200

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home
Chunk Length: 200

Chunk Number: 2
twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Ins
Chunk Length: 200

Chunk Number: 3
urance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

Chunk Length: 130


Chunk Size = 300

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expens
Chunk Length: 300

Chunk Number: 2
es are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

Chunk Length: 230

### **Analysis**
Are sentences being split?

Yes.

Is context preserved?

Partially.

Limitations?

Sentence boundaries are ignored and meaning may be lost.

# ***Task 3: Recursive Chunking***

In [9]:
!pip install langchain-text-splitters -q
from langchain_text_splitters import RecursiveCharacterTextSplitter

In [10]:
configs = [
    (200,20),
    (200,50),
    (300,50)
]

for size,overlap in configs:

    print(f"\nChunk Size={size}, Overlap={overlap}")

    splitter = RecursiveCharacterTextSplitter(
        chunk_size=size,
        chunk_overlap=overlap
    )

    chunks = splitter.split_text(text)

    for i,chunk in enumerate(chunks):

        print("\nChunk Number:",i+1)
        print(chunk)

Chunk Size=200, Overlap=20

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy

Chunk Number: 2
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.

Chunk Number: 3
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

Chunk Size=200, Overlap=50

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy

Chunk Number: 2
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy
Travel expenses are reimbursed within 30 days.

Chunk Number: 3
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.

Chunk Number: 4
Dependent coverage is available for spouse and children.

Chunk Size=300, Overlap=50

Chunk Number: 1
Leave Policy
Employees receive 12 casual leaves annually.
Employees receive 15 sick leaves annually.
Unused casual leaves cannot be carried forward.
Work From Home Policy
Employees may work from home twice per week.
Manager approval is required for additional remote work.
Travel Policy

Chunk Number: 2
Travel Policy
Travel expenses are reimbursed within 30 days.
Original receipts must be submitted for reimbursement.
Medical Insurance Policy
All employees are covered under company medical insurance.
Dependent coverage is available for spouse and children.

## **Analysis**

Overlap keeps some text from the previous chunk.

This prevents loss of context and improves retrieval accuracy.

# ***Task 4: Sentence Based Chunking***

In [12]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize

sentences = sent_tokenize(text)

for i,sentence in enumerate(sentences):

    print("Sentence Number:",i+1)
    print(sentence)
    print()

Sentence Number: 1
Leave Policy
Employees receive 12 casual leaves annually.

Sentence Number: 2
Employees receive 15 sick leaves annually.

Sentence Number: 3
Unused casual leaves cannot be carried forward.

Sentence Number: 4
Work From Home Policy
Employees may work from home twice per week.

Sentence Number: 5
Manager approval is required for additional remote work.

Sentence Number: 6
Travel Policy
Travel expenses are reimbursed within 30 days.

Sentence Number: 7
Original receipts must be submitted for reimbursement.

Sentence Number: 8
Medical Insurance Policy
All employees are covered under company medical insurance.

Sentence Number: 9
Dependent coverage is available for spouse and children.

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

## ***Analysis***

Sentence chunking preserves meaning better because complete
sentences remain together.

# ***Task 5: Semantic Chunking***

In [13]:
semantic_chunks = {
    "Leave Policy":
    """
    Employees receive 12 casual leaves annually.
    Employees receive 15 sick leaves annually.
    Unused casual leaves cannot be carried forward.
    """,

    "Work From Home Policy":
    """
    Employees may work from home twice per week.
    Manager approval is required for additional remote work.
    """,

    "Travel Policy":
    """
    Travel expenses are reimbursed within 30 days.
    Original receipts must be submitted for reimbursement.
    """,

    "Medical Insurance Policy":
    """
    All employees are covered under company medical insurance.
    Dependent coverage is available for spouse and children.
    """
}

In [14]:
for i,(title,chunk) in enumerate(semantic_chunks.items()):

    print(f"\nSemantic Chunk {i+1}")
    print(title)
    print(chunk)

Semantic Chunk 1
Leave Policy

    Employees receive 12 casual leaves annually.
    Employees receive 15 sick leaves annually.
    Unused casual leaves cannot be carried forward.


Semantic Chunk 2
Work From Home Policy

    Employees may work from home twice per week.
    Manager approval is required for additional remote work.


Semantic Chunk 3
Travel Policy

    Travel expenses are reimbursed within 30 days.
    Original receipts must be submitted for reimbursement.


Semantic Chunk 4
Medical Insurance Policy

    All employees are covered under company medical insurance.
    Dependent coverage is available for spouse and children.

### ***Analysis***

Semantic chunking groups related information together.

This improves retrieval because complete topics remain in a single chunk.

# ***Task 6: Comparison Table***

In [15]:
import pandas as pd

comparison = pd.DataFrame({

"Chunking Method":[
"Fixed Size",
"Recursive",
"Sentence",
"Semantic"
],

"Context Preservation":[
"Low",
"High",
"High",
"Very High"
],

"Retrieval Quality":[
"Medium",
"High",
"High",
"Very High"
],

"Implementation Complexity":[
"Easy",
"Medium",
"Easy",
"Hard"
]
})

comparison

,Chunking Method,Context Preservation,Retrieval Quality,Implementation Complexity
0,Fixed Size,Low,Medium,Easy
1,Recursive,High,High,Medium
2,Sentence,High,High,Easy
3,Semantic,Very High,Very High,Hard

# ***Task 7: Retrieval Simulation***

In [16]:
queries = [
"How many casual leaves are provided?",
"Can employees work from home?",
"What is the travel reimbursement process?",
"Who is covered under medical insurance?"
]

In [17]:
for q in queries:

    print("\nQuery:",q)

    if "casual" in q.lower():
        print("Retrieved Chunk:")
        print(semantic_chunks["Leave Policy"])

    elif "home" in q.lower():
        print("Retrieved Chunk:")
        print(semantic_chunks["Work From Home Policy"])

    elif "travel" in q.lower():
        print("Retrieved Chunk:")
        print(semantic_chunks["Travel Policy"])

    elif "insurance" in q.lower():
        print("Retrieved Chunk:")
        print(semantic_chunks["Medical Insurance Policy"])

    print("Chunking Method: Semantic")

Query: How many casual leaves are provided?
Retrieved Chunk:

    Employees receive 12 casual leaves annually.
    Employees receive 15 sick leaves annually.
    Unused casual leaves cannot be carried forward.

Chunking Method: Semantic

Query: Can employees work from home?
Retrieved Chunk:

    Employees may work from home twice per week.
    Manager approval is required for additional remote work.

Chunking Method: Semantic

Query: What is the travel reimbursement process?
Retrieved Chunk:

    Travel expenses are reimbursed within 30 days.
    Original receipts must be submitted for reimbursement.

Chunking Method: Semantic

Query: Who is covered under medical insurance?
Retrieved Chunk:

    All employees are covered under company medical insurance.
    Dependent coverage is available for spouse and children.

Chunking Method: Semantic

# ***Task 8: Recommendation Report***

In [18]:
report = pd.DataFrame({

"Assistant":[
"HR Policy Assistant",
"Legal Document Assistant",
"Medical Document Assistant",
"Research Paper Assistant"
],

"Recommended Chunking":[
"Semantic",
"Recursive + Overlap",
"Semantic",
"Recursive + Semantic Hybrid"
]
})

report

                    Assistant         Recommended Chunking
0         HR Policy Assistant                     Semantic
1    Legal Document Assistant          Recursive + Overlap
2  Medical Document Assistant                     Semantic
3    Research Paper Assistant  Recursive + Semantic Hybrid

# ***Conclusion***

In [19]:
print("""
Conclusion

Fixed Size Chunking:
Simple but may break sentences.

Recursive Chunking:
Better context retention through overlap.

Sentence Chunking:
Preserves sentence meaning.

Semantic Chunking:
Best retrieval quality and most suitable for enterprise RAG systems.
""")

Conclusion

Fixed Size Chunking:
Simple but may break sentences.

Recursive Chunking:
Better context retention through overlap.

Sentence Chunking:
Preserves sentence meaning.

Semantic Chunking:
Best retrieval quality and most suitable for enterprise RAG systems.